server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: helgather

  datasource:
    url: jdbc:mysql://hel-gather-db.cps699alalgs.ap-northeast-2.rds.amazonaws.com:3306/hel_gather_prod?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: kingjihong
    password: aA1349529!!!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
cloud:
  aws:
    s3:
      bucket: hel-gather
    credentials:
      access-key: AKIATNMKTXLNOOG6SY7F
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

