server:
  port: 8080

spring:
  application:
    name: helgather

  security:
    user:
      name: user
      password: password

  datasource:
    url: jdbc:mysql://hel-gather-db.cps699alalgs.ap-northeast-2.rds.amazonaws.com:3306/hel_gather_prod?serverTimezone=UTC&characterEncoding=UTF-8
    username: kingjihong
    password: aA1349529!!!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true