
spring:
  profiles:
    active: local
    group:
      local: common, local-db
      prod1: common, prod-db, prod1-server
      prod2: common, prod-db, prod2-server

server:
  env: blue

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

jasypt:
  encryptor:
    bean: jasyptEncryptorAES

cloud:
  aws:
    s3:
      bucket: hel-gather-s3
    credentials:
      access-key: ENC(X6mP91P3GtjXmsn1HRqSUR1jzPzi/F4/6sJKc9YyYfh7sSVhSnQOpwijUAnvlC60RI5gEVOd5nFLwzK/X0jgig==)
      secret-key: ENC(K3UNLT8RnQLkQ1ACC9YTCb6syCkVDg91U8RQHVieqG04j9Npw55Ixm5xvWCQh3a+cUvqbxcoyRwi6jbWmS7rReSp7KqmQkFWwRv00Su8ZJY=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

---

spring:
  config:
    activate:
      on-profile: common

servlet:
  multipart:
    max-file-size: 20MB
    max-request-size: 20MB

application:
  name: helgather

serverName: common
---

spring:
  config:
    activate:
      on-profile: local-db

datasource:
  url: jdbc:h2:tcp://localhost/~/helgather
  username: kingjihong
  password: aA1349529!!!!

jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true
      show_sql: true
dbInfo: h2

---

spring:
  config:
    activate:
      on-profile: prod-db

datasource:
  url: ENC(4h35jdBKUxNmd3F9HqNzPmKMI1FQfknTbRK/9R25bOvSG7tUgYd7UxCCrZuUSrJBmrauBQpjdZGjZY91QHP5U/GsZm0HG1xUXcPT/UHd0UJuQjr2nkLOajdZAydlonhUbdxgt3R17wTtudlrbhjaUT3KDrLZkthitdpDBSilUjcl3GH7K6XUKbXxCpC9T6+sqcRi/iVxjRUkaCN7a1nG+FcHjN2LBDdhLRP2fmyvpkIW50Tcb4jwrJIlISpPgZrmDvsT+9H2wiS9q78aTQzMcg==)
  username: ENC(IoypxQU/L2gWg4z/XTbzmSNVTelD0HfRhmpOYSgxy/jQcK+EeJPEUVFnq6wVK4Mp)
  password: ENC(7qwkjtEPdsPqgic+P3btJSd9i6qUldsDKPE6pmyHuxb1ipr5wtu/o8J93hs4MaZS)

jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true
      show_sql: true
dbInfo: rds

---

spring:
  config:
    activate:
      on-profile: prod1-server

serverName: hel-gather-prod1

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: prod2-server

serverName: hel-gather-prod2

server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: prod3-server

serverName: hel-gather-prod3

server:
  port: 8080

---